config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :countries
    resources :cities
    resources :candidate_types
    resources :candidates do
      collection do
        get 'progress'
        post 'progress_update'
        get 'probability_candidates'
        get 'import_csv_new'
        post 'import_csv'
      end
      get 'reply'
      get 'meeting'
    end
    get 'pages/setting' => "pages#setting"
  end
  root :to => 'admin/candidates#index'
end

app/models/candidate.rb
require 'csv'
require 'kconv'
class Candidate < ActiveRecord::Base
  belongs_to :city
  belongs_to :country
  belongs_to :candidate_type

  has_many :candidate_memos
  accepts_nested_attributes_for :candidate_memos, reject_if: proc {|memos| memos['name'].blank? }
  has_many :candidate_details
  accepts_nested_attributes_for :candidate_details, reject_if: proc {|details| details['sns_link'].blank? }
  has_one :candidate_progress
  accepts_nested_attributes_for :candidate_progress

  validates :name, presence: true

  STATUS = { "got_contact" => 1, "approached_with_linkedin" => 2, "approached_with_email" => 3, "approached_with_xing" => 4, "approached_with_facebook" => 5}
  Probability = {"No" => 0, "Yes" => 1}

end

app/models/candidate_detail.rb
class CandidateDetail < ActiveRecord::Base
  belongs_to :candidate

  KIND = { "LinkedIn" => 1, "Xing" => 2, "Facebook" => 3}
end

app/models/candidate_memo.rb
class CandidateMemo < ActiveRecord::Base
  belongs_to :candidate
end

app/models/candidate_progress.rb
class CandidateProgress < ActiveRecord::Base
  belongs_to :candidate
end

app/models/candidate_type.rb
class CandidateType < ActiveRecord::Base
  has_many :candidates
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :candidates
  belongs_to :country
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :candidates
  has_many :cities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
# -*- encoding: utf-8 -*-
class Admin::BaseController < ApplicationController
  layout 'admin'

  before_filter :authenticate_user!
  before_filter :basic_auth
end

app/controllers/admin/candidate_types_controller.rb
class Admin::CandidateTypesController < Admin::BaseController
  def index
    @candidate_types = CandidateType.all
    render layout: 'no_sidebar'
  end

  def new
    @candidate_type = CandidateType.new
    render layout: 'no_sidebar'
  end

  def create
    @candidate_type = CandidateType.new(candidate_type_params)
    if @candidate_type.save
      redirect_to admin_candidate_types_path
    else
      render "new"
    end
  end

  def candidate_type_params
    params.require(:candidate_type).permit(:title)
  end
end

app/controllers/admin/candidates_controller.rb
class Admin::CandidatesController < Admin::BaseController
  def index
    @query = Candidate.search(params[:q])
    @candidates = @query.result(distict: true).order('created_at DESC')
  end

  def show
    @candidate = Candidate.find(params[:id])
    @candidate_details = @candidate.candidate_details.sort
    @candidate_memos = @candidate.candidate_memos.sort
    render layout: 'no_sidebar'
  end

  def new
    @candidate = Candidate.new
    @candidate.candidate_memos.build
    @candidate.candidate_details.build
    render layout: 'no_sidebar'
  end

  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      redirect_to admin_candidates_path
    else
      @candidate.candidate_memos.build
      @candidate.candidate_details.build
      render "new", layout: 'no_sidebar'
    end
  end

  def edit
    @candidate = Candidate.find(params[:id])
    @candidate.candidate_details.build
    @candidate.candidate_memos.build
    render layout: 'no_sidebar'
  end

  def update
    @candidate = Candidate.find(params[:id])
    if @candidate.update_attributes(candidate_params)
      redirect_to admin_candidates_path
    else
      render 'edit', layout: 'no_sidebar'
    end
  end

  def progress
    @query = Candidate.search(params[:q])
    @candidates = @query.result(distict: true).order('created_at DESC')
  end

  def progress_update
    @candidate_ids = params[:candidates]
    @candidate_ids.each do |id|
      @candidate = Candidate.find(id)
      @candidate_progress = @candidate.candidate_progress
      if @candidate_progress.present?
        @candidate_progress.update(candidate_id: id, sent_at: Date.today)
      else
        @candidate_progress = CandidateProgress.new(candidate_id: id, sent_at: Date.today)
        @candidate_progress.save
      end
    end
    redirect_to progress_admin_candidates_path
  end

  def probability_candidates
    @query = Candidate.search(params[:q])
    @candidates = @query.result(distict: true).where(probability: 1).order('created_at DESC')
  end

  def reply
    @candidate = Candidate.find(params[:candidate_id])
    @candidate_progress = @candidate.candidate_progress
    if @candidate_progress.present?
      @candidate_progress.update(replied_at: Date.today)
    else
      @candidate_progress = CandidateProgress.new(candidate_id: params[:candidate_id], replied_at: Date.today)
      @candidate_progress.save
    end
    redirect_to progress_admin_candidates_path
  end

  def meeting
    @candidate = Candidate.find(params[:candidate_id])
    @candidate_progress = @candidate.candidate_progress
    if @candidate_progress.present?
      @candidate_progress.update(meeting_at: Date.today)
    else
      @candidate_progress = CandidateProgress.new(candidate_id: params[:candidate_id], meeting_at: Date.today)
      @candidate_progress.save
    end
    redirect_to progress_admin_candidates_path
  end

  def setting
    render layout: 'no_sidebar'
  end

  def import_csv_new
    render layout: 'no_sidebar'
  end

  def import_csv
    if params[:csv_file].blank?
      redirect_to import_csv_new_admin_candidates_path
    else
      candidates = csv_save(params[:csv_file])
      candidates.each do |candidate|
        candidate.save
      end
      redirect_to admin_candidates_path
    end
  end

  private
  def self.sort
    order('created_at DESC')
  end

  def candidate_params
    params.require(:candidate).permit(:id, :name,:country_id,:city_id,:personal_url,:kind,:phone,:email,:image,:status,:probability, {candidate_details_attributes: [:id, :_destroy, :candidate_id,:kind,:sns_link]}, {candidate_memos_attributes: [:id, :_destroy, :candidate_id,:name,:memo]}, {candidate_progress_attributes: [:id, :_destroy, :candidate_id, :sent_at, :replied_at, :meeting_at]})
  end

  def csv_save(csv_file)
    require 'csv'
    require 'kconv'

    charactor = csv_file.read
    datas = []

    CSV.parse(charactor.kconv(Kconv::UTF8, Kconv::SJIS), headers: true) do |row|

      candidate = Candidate.new
      candidate.name = row[0]
      candidate.country_id = row[1]
      candidate.city_id = row[2]
      candidate.candidate_type_id = row[3]
      candidate.personal_url = row[4]
      candidate.phone = row[5]
      candidate.email = row[6]
      candidate.image = row[7]
      candidate.status = 1
      datas << candidate
    end
    datas
  end
end

app/controllers/admin/cities_controller.rb
class Admin::CitiesController < Admin::BaseController
  def index
    @cities = City.all
    render layout: 'no_sidebar'
  end

  def new
    @city = City.new
    render layout: 'no_sidebar'
  end

  def create
    @city = City.new(city_params)
    if @city.save
      redirect_to admin_cities_path
    else
      render "new"
    end
  end

  def city_params
    params.require(:city).permit(:country_id, :title)
  end

end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < Admin::BaseController
  def index
    @countries = Country.all
    render layout: 'no_sidebar'
  end

  def new
    @country = Country.new
    render layout: 'no_sidebar'
  end

  def create
    @country = Country.new(country_params)
    if @country.save
      redirect_to admin_countries_path
    else
      render "new"
    end
  end

  def country_params
    params.require(:country).permit(:title)
  end


end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::BaseController
  def setting
    render layout: 'no_sidebar'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/candidate_types/_form.html.slim
= form_for [:admin, @candidate_type], html: {class: "form-horizontal"} do |f|
  div.control-group
    = f.label :candidate_type, class: 'control-label'
    div.controls
      = f.text_field :title
  = f.submit 'SUBMIT', class: 'btn btn-primary'

app/views/admin/candidate_types/_list.html.slim
table.table.table-striped
  thead
    tr
      th= CandidateType.human_attribute_name(:id)
      th= CandidateType.human_attribute_name(:title)
    tbody
      - @candidate_types.each do |i|
        tr
          td= i.id
          td= i.title

app/views/admin/candidate_types/index.html.slim
.page_header
  h1= 'CandidateTypes'
  = link_to "new", new_admin_candidate_type_path, class: 'btn btn-primary'
  = render partial: 'list'

app/views/admin/candidate_types/new.html.slim
.header 
  h1= 'CandidateTypeNew'
  = render partial: "admin/shared/errors", locals: {errors: @candidate_type.errors}
  = render partial: "form"

app/views/admin/candidates/_candidate_details.html.slim
- if @candidate_details.present?
  h3 Detail
  table.table
    - @candidate_details.each do |candidate_detail|
      tr
        th= CandidateDetail.human_attribute_name :kind
        td= candidate_detail.kind
      tr
        th= CandidateDetail.human_attribute_name :sns_link
        td= candidate_detail.sns_link

app/views/admin/candidates/_candidate_memos.html.slim
- if @candidate_memos.present?
  h3 Memos
  table.table
    - @candidate_memos.each do |candidate_memo|
      tr
        th= CandidateDetail.human_attribute_name :memo
        td
          = candidate_memo.memo
          small.text-info
            = candidate_memo.name

app/views/admin/candidates/_form.html.slim
= form_for [:admin, @candidate], html: {class: "form-horizontal"} do |f|
  div.control-group
    = f.label :name, class: 'control-label'
    div.controls
      = f.text_field :name
  div.control-group
    = f.label :country, class: 'control-label'
    div.controls
      = f.collection_select :country_id, Country.all, :id, :title, :include_blank => true
  div.control-group
    = f.label :city, class: 'control-label'
    div.controls
      = f.collection_select :city_id, City.all, :id, :title, :include_blank => true
  div.control-group
    = f.label :personal_url, class: 'control-label'
    div.controls
      = f.text_field :personal_url
  div.control-group
    = f.label :candidate_type, class: 'control-label'
    div.controls
      = f.collection_select :candidate_type_id, CandidateType.all, :id, :title, include_blank: true
  div.control-group
    = f.label :phone, class: 'control-label'
    div.controls
      = f.number_field :phone
  div.control-group
    = f.label :email, class: 'control-label'
    div.controls
      = f.text_field :email
  div.control-group
    = f.label :image_url, class: 'control-label'
    div.controls
      = f.text_field :image
  div.control-group
    = f.label :status, class: 'control-label'
    div.controls
      = f.select :status, Candidate::STATUS
  div.control-group
    = f.label :probability, class: 'control-label'
    div.controls
      = f.select :probability, Candidate::Probability
  = f.fields_for :candidate_details do |i|
    h3
      |SNS LINK
    div.control-group
      = i.label :kind, class: 'control-label'
      div.controls
        = i.select :kind, CandidateDetail::KIND
    div.control-group
      = i.label :sns_link, class: 'control-label'
      div.controls
        = i.text_field :sns_link
    = f.fields_for :candidate_memos do |j|
      h3
        |memo
      div.control-group
        = j.label :name, class: 'control-label'
        div.controls
          = j.text_field :name
      div.control-group
        = j.label :memo, class: 'control-label'
        div.controls
          = j.text_field :memo
  = f.submit 'SUBMIT', class: 'btn btn-primary'

app/views/admin/candidates/_form_progress.html.slim
table.table.table-striped
  thead
    tr
      th= Candidate.human_attribute_name(:id)
      th= Candidate.human_attribute_name(:name)
      th= Candidate.human_attribute_name(:place)
      th= Candidate.human_attribute_name(:sent_at)
      th= Candidate.human_attribute_name(:replied_at)
      th= Candidate.human_attribute_name(:meeting_at)
    tbody
      - @candidates.each do |candidate|
        tr
          td
            label.checkbox
              = check_box_tag 'candidates[]', candidate.id
              = candidate.id
          td= link_to candidate.name, admin_candidate_path(candidate)
          td
            -if candidate.country.present?
              = candidate.country.title
              |/
            -if candidate.city.present?
              = candidate.city.title
          - if candidate.candidate_progress.present? and candidate.candidate_progress.sent_at.present?
            td= candidate.candidate_progress.sent_at.strftime('%Y-%m-%d')
          - else
            td Not yet
          - if candidate.candidate_progress.present? and candidate.candidate_progress.replied_at.present?
            td= candidate.candidate_progress.replied_at.strftime('%Y-%m-%d')
          - else
            td Not yet
          - if candidate.candidate_progress.present? and candidate.candidate_progress.meeting_at.present?
            td= candidate.candidate_progress.meeting_at.strftime('%Y-%m-%d')
          - else
            td Not yet
          td= link_to 'Reply', admin_candidate_reply_path(candidate), class: 'btn btn-success'
          td= link_to 'Meeting', admin_candidate_meeting_path(candidate), class: 'btn btn-danger 	'

app/views/admin/candidates/_list.html.slim
table.table.table-striped
  thead
    tr
      th= Candidate.human_attribute_name(:id)
      th= Candidate.human_attribute_name(:name)
      th= Candidate.human_attribute_name(:place)
      th= Candidate.human_attribute_name(:link)
      th= Candidate.human_attribute_name(:edit)
  tbody
    - @candidates.each do |candidate|
      tr
        td= candidate.id
        td
          = link_to candidate.name, admin_candidate_path(candidate)
          small.muted
          - if candidate.candidate_type.present?
            = "(#{candidate.candidate_type.title})"
        td
          - if candidate.country.present?
            = candidate.country.title
            |/
            = candidate.city.title
        td
          -candidate.candidate_details.each do |detail|
            = link_to CandidateDetail::KIND.key(detail.kind), detail.sns_link
            | |
        td= link_to 'Edit', edit_admin_candidate_path(candidate), class: 'btn btn-success'

app/views/admin/candidates/_list_probability.html.slim
table.table.table-striped
  thead
    tr
      th= Candidate.human_attribute_name(:id)
      th= Candidate.human_attribute_name(:image)
      th= Candidate.human_attribute_name(:name)
      th= Candidate.human_attribute_name(:place)
      th= Candidate.human_attribute_name(:meeting)
  tbody
    - @candidates.each do |candidate|
      tr
        td= candidate.id
        td= image_tag candidate.image, class: 'img-circle', style: 'width: 60px;'
        td= link_to candidate.name, admin_candidate_path(candidate)
        td
          - if candidate.country.present?
            = candidate.country.title
            |/
          - if candidate.city.present?
            = candidate.city.title
        - if candidate.candidate_progress.present? and candidate.candidate_progress.meeting_at.present?
          td= candidate.candidate_progress.meeting_at.strftime('%Y-%m-%d')
        -else
          td Not yet

app/views/admin/candidates/edit.html.slim
.header
  h1= 'CandidateEdit'
  = render partial: "admin/shared/errors", locals: {errors: @candidate.errors}
= render partial: "form"

app/views/admin/candidates/import_csv_new.html.slim
h3 Import candidates
= form_tag({controller: "candidates", action: "import_csv", method: "post"}, {multipart: true}) do
  div.field
    = file_field_tag :csv_file, class: 'btn'
  div.action
    = submit_tag "Import CSV", class: 'btn btn-primary', style: 'margin: 10px;'
h3 Install CSV Template
= link_to 'temlate.csv', '/temlate.csv', class: 'btn btn-success'
h3 Precautions
|You should type id when if it has prefix "_id"
h4 country_id
small
  |refer to the URL 
= link_to 'Countries List', admin_countries_path
h4 city_id
small
  |refer to the URL 
= link_to 'Cities List', admin_cities_path
h4 candidate_type_id
small
  |refer to the URL 
= link_to 'Candidate Types List', admin_candidate_types_path

app/views/admin/candidates/index.html.slim
.page_header
  h1= 'Candidates'
  = link_to "new", new_admin_candidate_path, class: 'btn btn-primary'
  = render partial: 'list'

app/views/admin/candidates/new.html.slim
.header
  h1= 'CandidateNew'
  = render partial: "admin/shared/errors", locals: {errors: @candidate.errors}
= render partial: "form"

app/views/admin/candidates/probability_candidates.html.slim
.page_header
  h1= 'ProbabilityCandidates'
  = render partial: 'list_probability'

app/views/admin/candidates/progress.html.slim
.page_header
  h1= 'CandidatesProgress'
  = form_tag("/admin/candidates/progress_update", method: "post") do
    =submit_tag 'Approached', class: 'btn btn-primary'
    = render partial: 'form_progress'

app/views/admin/candidates/show.html.slim
.page-header
  h3
    |Candidate detail
  p= link_to 'Edit', edit_admin_candidate_path(@candidate.id), class: 'btn btn-success'
  table.table
    tr
      th= Candidate.human_attribute_name :id
      td= @candidate.id
    tr
      th= Candidate.human_attribute_name :name
      td= @candidate.name
    tr
      - if @candidate.country.present?
        th= Candidate.human_attribute_name :country
        td= @candidate.country.title
    tr
      - if @candidate.city.present?
        th= Candidate.human_attribute_name :city
        td= @candidate.city.title
    tr
      th= Candidate.human_attribute_name :personal_url
      td
        a href= @candidate.personal_url
          = @candidate.personal_url
    tr
      th= Candidate.human_attribute_name :phone
      td= @candidate.phone
    tr
      th= Candidate.human_attribute_name :email
      td= @candidate.email
    tr
      th= Candidate.human_attribute_name :image
      td= image_tag @candidate.image, class: 'img-circle', style: 'width: 150px;'
    tr
      th= Candidate.human_attribute_name :status
      td= Candidate::STATUS.key(@candidate.status.to_i)
    tr
      th= Candidate.human_attribute_name :probability
      td= Candidate::Probability.key(@candidate.probability.to_i)
    tr
      th= Candidate.human_attribute_name :created_at
      td= @candidate.created_at
    tr
      th= Candidate.human_attribute_name :updated_at
      td= @candidate.updated_at
  = render partial: 'candidate_details'
  = render partial: 'candidate_memos'

app/views/admin/cities/_form.html.slim
= form_for [:admin, @city], html: {class: "form-horizontal"} do |f|
  div.control-group
    = f.label :country, class: 'control-label'
    div.controls
      = f.collection_select :country_id, Country.all, :id, :title
  div.control-group
    = f.label :city, class: 'control-label'
    div.controls
      = f.text_field :title
  = f.submit 'SUBMIT', class: 'btn btn-primary'

app/views/admin/cities/_list.html.slim
table.table.table-striped
  thead
    tr
      th= City.human_attribute_name(:id)
      th= City.human_attribute_name(:county)
      th= City.human_attribute_name(:city)
  tbody
    - @cities.each do |city|
      tr
        td= city.id
        td= city.country.title
        td= city.title

app/views/admin/cities/index.html.slim
.pageheadr
  h1= 'Cities'
  = link_to "new", new_admin_city_path, class: 'btn btn-primary'
  = render partial: 'list'

app/views/admin/cities/new.html.slim
.header
  h1= 'CityNew'
  = render partial: "admin/shared/errors", locals: {errors: @city.errors}
= render partial: "form"

app/views/admin/countries/_form.html.slim
= form_for [:admin, @country], html: {class: "form-horizontal"} do |f|
  div.control-group
    = f.label :country, class: 'control-label'
    div.controls
      = f.text_field :title
  = f.submit 'SUBMIT', class: 'btn btn-primary'

app/views/admin/countries/_list.html.slim
table.table.table-striped
  thead
    tr
      th= Country.human_attribute_name(:id)
      th= Country.human_attribute_name(:title)
  tbody
    - @countries.each do |country|
      tr
        td= country.id
        td= country.title

app/views/admin/countries/index.html.slim
.page_header
  h1= 'Countries'
  = link_to "new", new_admin_country_path, class: 'btn btn-primary'
  = render partial: 'list'

app/views/admin/countries/new.html.slim
.header
  h1= 'CountryNew'
  = render partial: "admin/shared/errors", locals: {errors: @country.errors}
= render partial: "form"

app/views/admin/pages/setting.html.slim
.page_header
  h1= 'Setting'
  blockquote
    h3 ADD County
    small
      | -please check your speling before submit
    = link_to "Add Country", admin_countries_path, class: 'btn btn-info'
  blockquote
    h3 ADD City
    small
      | -please check your speling before submit
    = link_to "Add City", admin_cities_path, class: 'btn btn-info'
  blockquote
    h3 ADD CandidateType
    small
      | -please check your speling before submit
    = link_to "Add CandidateType", admin_candidate_types_path, class: 'btn btn-info'

app/views/admin/shared/_errors.html.slim
- if errors.present?
  = errors.full_messages.join

app/views/layouts/_header.html.slim
li= link_to "Progress", progress_admin_candidates_path
li= link_to "Probability", probability_candidates_admin_candidates_path
li= link_to "Setting", admin_pages_setting_path
li= link_to "Import CSV", import_csv_new_admin_candidates_path

app/views/layouts/admin.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "CandidateManager"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="/admin/candidates" CandidateManager
          .container-fluid.nav-collapse
            ul.nav
              = render partial: 'layouts/header'

    .container-fluid
      .row-fluid
        .span3
          .well.sidebar-nav
            ul.nav.nav-list
              li.nav-header Search
              p
                = search_form_for @query, url: request.url, html: {class: 'form-horizonta'} do |f|
                  div.input-prepend
                    span.add-on
                      |id
                    = f.text_field :id_eq, class: 'input-small'
                  div.input-prepend
                    span.add-on
                      |name
                    = f.text_field :name_cont, class: 'input-small'
                  div.input-prepend
                    span.add-on
                      |country
                    = f.collection_select :country_id_eq, Country.all, :id, :title, {prompt: ''}, {class: 'span8'}
                  div.input-prepend
                    span.add-on
                      |city
                    = f.select :city_id_eq, City.all.map {|u| [u.title, u.id] }, {prompt: ''}, {class: 'span18'}
                  div.input-prepend
                    span.add-on
                      |type
                    = f.collection_select :candidate_type_id_eq, CandidateType.all, :id, :title, {prompt: ''}, {class: 'span18'}
                  li 
                    = f.submit "search", class: 'btn'
        .span9
          = bootstrap_flash
          = yield

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "AppointmentManager"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body

    .container-fluid
      = bootstrap_flash
      = yield

app/views/layouts/no_sidebar.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "CandidateManager"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="/admin/candidates" CandidateManager
          .container-fluid.nav-collapse
            ul.nav
              = render partial: 'layouts/header'

    .container-fluid
      .row-fluid
        = bootstrap_flash
        = yield